#!/bin/bash -fe

# EAMxx template run script

main() {

do_fetch_code=false
do_create_newcase=true
do_case_setup=true
do_case_build=false
do_case_submit=true

readonly MACHINE="pm-gpu"
readonly BRANCH="29bdb81"
readonly CHERRY=( )
readonly COMPILER="gnugpu"
readonly DEBUG_COMPILE=FALSE
readonly QUEUE=regular

# MPS settings
readonly MPS_YES=FALSE
readonly MPS_NOS=8

# Simulation
readonly COMPSET="F2010-SCREAMv1"
readonly RES="256"
readonly RESOLUTION="ne${RES}pg2_ne${RES}pg2"

readonly SCREAMDOCS_ROOT="${PSCRATCH}/scream-docs"
readonly CODE_ROOT="${PSCRATCH}/scream-repo/${BRANCH}"
readonly PROJECT="e3sm_g"

readonly CASE_TYPE="pd"
readonly CASE_DESC="nudg"

readonly CASE_NAME=${CASE_TYPE}.${BRANCH}.${CASE_DESC}.${RES}
readonly CASE_ROOT="${PSCRATCH}/e3sm-scratch/${MACHINE}/${BRANCH}/${CASE_NAME}"

readonly CASE_GROUP=""

# History file frequency (if using default above)
readonly HIST_OPTION="never"
readonly HIST_N="1"

# Run options
readonly MODEL_START_TYPE="initial"  # "initial", "continue", "branch", "hybrid"
readonly START_DATE="2019-08-01"     # "" for default, or explicit "0001-01-01"

# Additional options for 'branch' and 'hybrid'
readonly GET_REFCASE=false
readonly RUN_REFDIR=""
readonly RUN_REFCASE=""
readonly RUN_REFDATE=""   # same as MODEL_START_DATE for 'branch', can be different for 'hybrid'

# Sub-directories
readonly CASE_BUILD_DIR=${CASE_ROOT}/build
readonly CASE_ARCHIVE_DIR=${CASE_ROOT}/archive

readonly CASE_SCRIPTS_DIR=${CASE_ROOT}/redux/case_scripts
readonly CASE_RUN_DIR=${CASE_ROOT}/redux/run
# readonly PELAYOUT="384x1" # 96 nodes
if [[ ${RESOLUTION} == "ne1024pg2_ne1024pg2" ]]; then
    readonly NUM_PES=512
elif [[ ${RESOLUTION} == "ne256pg2_ne256pg2" ]]; then
    readonly NUM_PES=192
else
    echo "Invalid resolution: ${RESOLUTION}"
    exit
fi
if [[ ${MPS_YES} == "TRUE" ]]; then
    readonly PEL_SIM=$(( MPS_NOS * NUM_PES ))
else
    readonly PEL_SIM=$(( 4 * NUM_PES ))
fi
echo "PEL_SIM = ${PEL_SIM}"
readonly PELAYOUT=${PEL_SIM}"x1"
if [[ ${RES} == "256" ]]; then
    readonly WALLTIME="18:00:00"
    readonly STOP_OPTION="nmonths"
    readonly STOP_N="13"
    readonly REST_OPTION="nmonths"
    readonly REST_N="1"
    readonly RESUBMIT="0"
elif [[ ${RES} == "1024" ]]; then
    readonly WALLTIME="23:00:00"
    readonly STOP_OPTION="ndays"
    readonly STOP_N="35"
    readonly REST_OPTION="ndays"
    readonly REST_N="7"
    readonly RESUBMIT="12"
else
    echo "Invalid resolution: ${RES}"
    exit
fi
readonly DO_SHORT_TERM_ARCHIVING=false

# Leave empty (unless you understand what it does)
readonly OLD_EXECUTABLE="/pscratch/sd/m/mahf708/e3sm-scratch/pm-gpu/29bdb81-241130/pd.29bdb81-241130.nudg.256/build/e3sm.exe"

# Make directories created by this script world-readable
umask 022

# Fetch code from Github
fetch_code

githash_eamxx=`git --git-dir ${CODE_ROOT}/.git rev-parse HEAD`
githash_screamdocs=`git --git-dir ${SCREAMDOCS_ROOT}/.git rev-parse HEAD`

# Create case
create_newcase

# Setup
case_setup

# Build
case_build

# Configure runtime options
runtime_options

# Copy script into case_script directory for provenance
copy_script

# Submit
case_submit

# All done
echo $'\n----- All done -----\n'

}

# =======================
# Custom user_nl settings
# =======================

user_nl() {

    echo "+++ Configuring SCREAM for 128 vertical levels +++"
    ./xmlchange SCREAM_CMAKE_OPTIONS="SCREAM_NP 4 SCREAM_NUM_VERTICAL_LEV 128 SCREAM_NUM_TRACERS 10"

}

######################################################
### Most users won't need to change anything below ###
######################################################

#-----------------------------------------------------
fetch_code() {

    if [ "${do_fetch_code,,}" != "true" ]; then
	echo $'\n----- Skipping fetch_code -----\n'
	return
    fi

    echo $'\n----- Starting fetch_code -----\n'
    local path=${CODE_ROOT}
    local repo=scream

    echo "Cloning $repo repository branch $BRANCH under $path"
    if [ -d "${path}" ]; then
	echo "ERROR: Directory already exists. Not overwriting"
	exit 20
    fi
    mkdir -p ${path}
    pushd ${path}

    # This will put repository, with all code
    git clone git@github.com:E3SM-Project/${repo}.git .

    # Q: DO WE NEED THIS FOR EAMXX?
    # Setup git hooks
    rm -rf .git/hooks
    git clone git@github.com:E3SM-Project/E3SM-Hooks.git .git/hooks
    git config commit.template .git/hooks/commit.template

    # Check out desired branch
    git checkout ${BRANCH}

    # Custom addition
    if [ "${CHERRY}" != "" ]; then
	echo ----- WARNING: adding git cherry-pick -----
	for commit in "${CHERRY[@]}"
	do
	    echo ${commit}
	    git cherry-pick ${commit}
	done
	echo -------------------------------------------
    fi

    # Bring in all submodule components
    git submodule update --init --recursive

    popd
}

#-----------------------------------------------------
create_newcase() {

    if [ "${do_create_newcase,,}" != "true" ]; then
	echo $'\n----- Skipping create_newcase -----\n'
	return
    fi

    echo $'\n----- Starting create_newcase -----\n'

    # Base arguments
    args=" --case ${CASE_NAME} \
	--output-root ${CASE_ROOT} \
	--script-root ${CASE_SCRIPTS_DIR} \
	--handle-preexisting-dirs u \
	--compset ${COMPSET} \
	--res ${RESOLUTION} \
	--machine ${MACHINE} \
	--compiler ${COMPILER} \
	--walltime ${WALLTIME} \
	--pecount ${PELAYOUT}"

    # Oprional arguments
    if [ ! -z "${PROJECT}" ]; then
      args="${args} --project ${PROJECT}"
    fi
    if [ ! -z "${CASE_GROUP}" ]; then
      args="${args} --case-group ${CASE_GROUP}"
    fi
    if [ ! -z "${QUEUE}" ]; then
      args="${args} --queue ${QUEUE}"
    fi

    ${CODE_ROOT}/cime/scripts/create_newcase ${args}

    if [ $? != 0 ]; then
      echo $'\nNote: if create_newcase failed because sub-directory already exists:'
      echo $'  * delete old case_script sub-directory'
      echo $'  * or set do_newcase=false\n'
      exit 35
    fi

}

#-----------------------------------------------------
case_setup() {

    if [ "${do_case_setup,,}" != "true" ]; then
	echo $'\n----- Skipping case_setup -----\n'
	return
    fi

    echo $'\n----- Starting case_setup -----\n'
    pushd ${CASE_SCRIPTS_DIR}

    # Setup some CIME directories
    ./xmlchange EXEROOT=${CASE_BUILD_DIR}
    ./xmlchange RUNDIR=${CASE_RUN_DIR}

    # Short term archiving
    ./xmlchange DOUT_S=${DO_SHORT_TERM_ARCHIVING}
    ./xmlchange DOUT_S_ROOT=${CASE_ARCHIVE_DIR}

    # Extracts input_data_dir in case it is needed for user edits to the namelist later
    local input_data_dir=`./xmlquery DIN_LOC_ROOT --value`

    # Custom user_nl
    user_nl

    if [[ ${MPS_YES} == "TRUE" ]]; then
        # MPS settings
        readonly MPS_NUMBER=${MPS_NOS}
    else
        # No MPS
        readonly MPS_NUMBER=4
    fi

    if [[ ${MPS_YES} == "TRUE" ]]; then
        ./xmlchange --file env_mach_pes.xml MAX_MPITASKS_PER_NODE="${MPS_NUMBER}"
        ./xmlquery --file env_mach_pes.xml MAX_MPITASKS_PER_NODE
    fi

    ./xmlchange --file env_mach_pes.xml NTHRDS="1"
    ./xmlchange --file env_mach_pes.xml NTHRDS_ATM="1"
    ./xmlchange --file env_mach_pes.xml NTHRDS_LND="$(( 64 / MPS_NUMBER ))"
    ./xmlquery NTHRDS_LND
    ./xmlchange --file env_mach_pes.xml NTHRDS_ICE="$(( 64 / MPS_NUMBER ))"
    ./xmlquery NTHRDS_ICE
    ./xmlchange --file env_mach_pes.xml NTHRDS_OCN="1"
    ./xmlchange --file env_mach_pes.xml NTHRDS_ROF="1"
    ./xmlchange --file env_mach_pes.xml NTHRDS_CPL="1"
    ./xmlchange --file env_mach_pes.xml NTHRDS_GLC="1"
    ./xmlchange --file env_mach_pes.xml NTHRDS_WAV="1"

    ./xmlchange PIO_NETCDF_FORMAT="64bit_data"
    
    # Finally, run CIME case.setup
    ./case.setup --reset

    if [[ ${MPS_YES} == "TRUE" ]]; then
        # Use the mps wrapper
        ./xmlchange run_exe="${PSCRATCH}/mps-wrapper.sh `./xmlquery --value run_exe`"
        ./xmlquery run_exe
    fi

    # Save provenance invfo
    echo "branch hash for EAMxx: $githash_eamxx" > GIT_INFO.txt
    echo "master hash for output files: $githash_screamdocs" >> GIT_INFO.txt

    popd
}

#-----------------------------------------------------
case_build() {

    pushd ${CASE_SCRIPTS_DIR}

    # do_case_build = false
    if [ "${do_case_build,,}" != "true" ]; then

	echo $'\n----- case_build -----\n'

	if [ "${OLD_EXECUTABLE}" == "" ]; then
	    # Ues previously built executable, make sure it exists
	    if [ -x ${CASE_BUILD_DIR}/e3sm.exe ]; then
		echo 'Skipping build because $do_case_build = '${do_case_build}
	    else
		echo 'ERROR: $do_case_build = '${do_case_build}' but no executable exists for this case.'
		exit 297
	    fi
	else
	    # If absolute pathname exists and is executable, reuse pre-exiting executable
	    if [ -x ${OLD_EXECUTABLE} ]; then
		echo 'Using $OLD_EXECUTABLE = '${OLD_EXECUTABLE}
		cp -fp ${OLD_EXECUTABLE} ${CASE_BUILD_DIR}/
	    else
		echo 'ERROR: $OLD_EXECUTABLE = '$OLD_EXECUTABLE' does not exist or is not an executable file.'
		exit 297
	    fi
	fi
	echo 'WARNING: Setting BUILD_COMPLETE = TRUE.  This is a little risky, but trusting the user.'
	./xmlchange BUILD_COMPLETE=TRUE

    # do_case_build = true
    else

	echo $'\n----- Starting case_build -----\n'

	# Turn on debug compilation option if requested
	if [ "${DEBUG_COMPILE}" == "TRUE" ]; then
	    ./xmlchange DEBUG=${DEBUG_COMPILE}
	fi

	# Run CIME case.build
	./case.build

	# Some user_nl settings won't be updated to *_in files under the run directory
	# Call preview_namelists to make sure *_in and user_nl files are consistent.
	./preview_namelists

    fi

    popd
}

#-----------------------------------------------------
runtime_options() {

    echo $'\n----- Starting runtime_options -----\n'
    pushd ${CASE_SCRIPTS_DIR}

    local input_data_dir=`./xmlquery DIN_LOC_ROOT --value`

    # Set simulation start date
    if [ ! -z "${START_DATE}" ]; then
	./xmlchange RUN_STARTDATE=${START_DATE}
    fi

    # Set temperature cut off in dycore threshold to 180K
    ./atmchange vtheta_thresh=180
    ./atmquery vtheta_thresh

    ./atmchange physics::atm_procs_list="mac_aero_mic,rrtmgp,cosp,nudging"

    # Set cosp default frequency
    ./atmchange physics::cosp::cosp_frequency_units="hours"
    ./atmchange physics::cosp::cosp_frequency=1

    # Turn on turbulent mountain stress
    ./atmchange physics::mac_aero_mic::atm_procs_list="tms,shoc,cldFraction,spa,p3"

    ./atmchange initial_conditions::Filename="${input_data_dir}/atm/scream/init/screami_ne${RES}np4L128_era5-20190801-topoadjx6t_20230620.nc"

    ./atmchange physics::mac_aero_mic::shoc::compute_tendencies=T_mid,qv
    ./atmchange physics::mac_aero_mic::p3::compute_tendencies=T_mid,qv
    ./atmchange physics::rrtmgp::compute_tendencies=T_mid
    ./atmchange homme::compute_tendencies=T_mid,qv

    # use GHG levels more appropriate for 2019
    ./atmchange co2vmr=410.5e-6
    ./atmchange ch4vmr=1877.0e-9
    ./atmchange n2ovmr=332.0e-9
    ./atmchange orbital_year=2019
    # use CO2 the same in land model
    ./xmlchange CCSM_CO2_PPMV=410.5
    #write out DAG
    #./atmchange atmosphere_dag_verbosity_level=5

    if [ ${CASE_TYPE} == "pd" ]; then
        echo "+++ CHANGING SPA FILE +++"
        ./atmchange spa_data_file="\$DIN_LOC_ROOT/atm/scream/init/spa_from_eamv3.ne30pg2.F2010.2011-2040.c_20240405.nc"
        ./atmquery spa_data_file
    elif [ ${CASE_TYPE} == "pi" ]; then
        echo "+++ CHANGING SPA FILE +++"
        ./atmchange spa_data_file="\$DIN_LOC_ROOT/atm/scream/init/spa_from_eamv3.ne30pg2.F2010.pi.2011-2040.c_20240405.nc"
        ./atmquery spa_data_file
    fi

    ./atmchange nudging::nudging_filenames_patterns="${PSCRATCH}/mo_ne45pg2_nudg_trim_merra/*.nc"
    ./atmquery nudging::nudging_filenames_patterns

    ./atmchange nudging::source_pressure_type=TIME_DEPENDENT_3D_PROFILE
    ./atmquery nudging::source_pressure_type
    ./atmchange nudging::nudging_fields=U,V
    ./atmquery nudging::nudging_fields
    ./atmchange nudging::nudging_timescale=21600
    ./atmquery nudging::nudging_timescale
    ./atmchange nudging::nudging_refine_remap_mapfile="${PSCRATCH}/map_ne45pg2_to_ne${RES}pg2.trbilin.20240410.nc"
    ./atmquery nudging::nudging_refine_remap_mapfile

    ./atmchange extra_clnclrsky_diag=true
    ./atmchange extra_clnsky_diag=true

    #specify land IC file
    if [[ ${RES} == "256" ]]; then
        readonly FINIDATA_FILE="${input_data_dir}/lnd/clm2/initdata/20230522.I2010CRUELM.ne256pg2.elm.r.2013-08-01-00000.nc"
    elif [[ ${RES} == "1024" ]]; then
        readonly FINIDATA_FILE="${input_data_dir}/lnd/clm2/initdata/20220928.I2010CRUELM.ne1024pg2_ICOS10.elm.r.2016-08-01-00000.nc"
    else
        echo "RES must be 256 or 1024"
        exit 1
    fi

cat << EOF >> user_nl_elm
 finidat="${FINIDATA_FILE}"
 hist_empty_htapes=.true.
EOF

cat << EOF >> user_nl_cpl
 ocn_surface_flux_scheme = 2
EOF

cat << EOF >> user_nl_cice
 histfreq = 'x','x','x','x','x'
 histfreq_n = 0,0,0,0,0
EOF

    # Segment length
    ./xmlchange STOP_OPTION=${STOP_OPTION,,},STOP_N=${STOP_N}

    # Restart frequency
    ./xmlchange REST_OPTION=${REST_OPTION,,},REST_N=${REST_N}

    # Coupler history
    ./xmlchange HIST_OPTION=${HIST_OPTION,,},HIST_N=${HIST_N}

    # Coupler budgets (always on)
    ./xmlchange BUDGETS=TRUE

    # Set resubmissions
    if (( RESUBMIT > 0 )); then
	./xmlchange RESUBMIT=${RESUBMIT}
    fi

    # Run type
    # Start from default of user-specified initial conditions
    if [ "${MODEL_START_TYPE,,}" == "initial" ]; then
	./xmlchange RUN_TYPE="startup"
	./xmlchange CONTINUE_RUN="FALSE"

    # Continue existing run
    elif [ "${MODEL_START_TYPE,,}" == "continue" ]; then
	./xmlchange CONTINUE_RUN="TRUE"

    elif [ "${MODEL_START_TYPE,,}" == "branch" ] || [ "${MODEL_START_TYPE,,}" == "hybrid" ]; then
	./xmlchange RUN_TYPE=${MODEL_START_TYPE,,}
	./xmlchange GET_REFCASE=${GET_REFCASE}
	./xmlchange RUN_REFDIR=${RUN_REFDIR}
	./xmlchange RUN_REFCASE=${RUN_REFCASE}
	./xmlchange RUN_REFDATE=${RUN_REFDATE}
	echo 'Warning: $MODEL_START_TYPE = '${MODEL_START_TYPE}
	echo '$RUN_REFDIR = '${RUN_REFDIR}
	echo '$RUN_REFCASE = '${RUN_REFCASE}
	echo '$RUN_REFDATE = '${START_DATE}

    else
	echo 'ERROR: $MODEL_START_TYPE = '${MODEL_START_TYPE}' is unrecognized. Exiting.'
	exit 380
    fi

    # Copy output stream yaml files
    if [ "${RESOLUTION}" == "ne1024pg2_ne1024pg2" ]; then
        map_to_ne30="${input_data_dir}/atm/scream/maps/map_ne1024pg2_to_ne30pg2_mono.20230901.nc"
        map_to_DecadalSites="${input_data_dir}/atm/scream/maps/map_ne1024pg2_to_DecadalSites_c20240130.nc"
    elif [ "${RESOLUTION}" == "ne256pg2_ne256pg2" ]; then
        map_to_ne30="${input_data_dir}/atm/scream/maps/map_ne256pg2_to_ne30pg2_traave.20240206.nc"
        map_to_DecadalSites="${input_data_dir}/atm/scream/maps/map_ne256pg2_to_DecadalSites_c20240130.nc"
    else
        echo "Unsupported res for horiz maps"
        exit 1
    fi
    output_yaml_files=$(find $PSCRATCH/io_aero_sub_241130/ -maxdepth 1 -type f)
    for file in ${output_yaml_files[@]}; do
        # TODO: add remap file replacement for different grids
        cp -v ${file} ./
        if [ "${file}" == "${output_yaml_files[0]}" ]; then
            # First file, reset output list
            ./atmchange output_yaml_files="./`basename ${file}`"
        else
            # Append to output list
            ./atmchange output_yaml_files+="./`basename ${file}`"
        fi
        # Replace remap files
        sed -i "s|horiz_remap_file:.*_to_ne30.*|horiz_remap_file: ${map_to_ne30}|" ./`basename ${file}`
        sed -i "s|horiz_remap_file:.*_to_DecadalSites.*|horiz_remap_file: ${map_to_DecadalSites}|" ./`basename ${file}`
    done
    

    ./xmlchange --file env_run.xml --id SSTICE_DATA_FILENAME --val "${input_data_dir}/atm/cam/sst/sst_ostia_ukmo-l4_ghrsst_3600x7200_20190731_20200901_c20230913.nc"
    ./xmlchange --file env_run.xml --id SSTICE_GRID_FILENAME --val "${input_data_dir}/ocn/docn7/domain.ocn.3600x7200.230522.nc"
    ./xmlchange --file env_run.xml --id SSTICE_YEAR_ALIGN --val 2019
    ./xmlchange --file env_run.xml --id SSTICE_YEAR_START --val 2019
    ./xmlchange --file env_run.xml --id SSTICE_YEAR_END --val 2020

    if [ -z "${Q}" ]; then
        ./xmlchange JOB_QUEUE=${QUEUE}
    fi
    popd
}

#-----------------------------------------------------
case_submit() {

    if [ "${do_case_submit,,}" != "true" ]; then
	echo $'\n----- Skipping case_submit -----\n'
	return
    fi

    echo $'\n----- Starting case_submit -----\n'
    pushd ${CASE_SCRIPTS_DIR}

    # Run CIME case.submit
    ./case.submit -a="--mail-type=ALL --mail-user=$USER@nersc.gov"

    popd
}

#-----------------------------------------------------
copy_script() {

    echo $'\n----- Saving run script for provenance -----\n'
    local script_provenance_dir=${CASE_SCRIPTS_DIR}/run_script_provenance
    mkdir -p ${script_provenance_dir}
    local this_script_name=$( basename -- "$0"; )
    local this_script_dir=$( dirname -- "$0"; )
    local script_provenance_name=${this_script_name}.`date +%Y%m%d-%H%M%S`
    cp -vp "${this_script_dir}/${this_script_name}" ${script_provenance_dir}/${script_provenance_name}

}

#-----------------------------------------------------
# Silent versions of popd and pushd
pushd() {
    command pushd "$@" > /dev/null
}
popd() {
    command popd "$@" > /dev/null
}

# Now, actually run the script
#-----------------------------------------------------
main
