#!/bin/bash -fe

set -euxo pipefail

set_cdn="00"
set_pdx="D"
set_dms="20"

while getopts ":r:n:a:z:c:e:p:k:d:s:w:t:o:" opt; do
  case $opt in
    n) set_cdn=${OPTARG}
    ;;
    p) set_pdx=${OPTARG}
    ;;
    d) set_dms=${OPTARG}
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    exit 1
    ;;
  esac

  case $OPTARG in
    -*) echo "Option $opt needs a valid argument"
    exit 1
    ;;
  esac
done

echo "n${set_cdn}p${set_pdx}d${set_dms}"

# E3SM Coupled Model Group run_e3sm script template.
#
# Bash coding style inspired by:
# http://kfirlavi.herokuapp.com/blog/2012/11/14/defensive-bash-programming

# TO DO:
# - custom pelayout

main() {

# For debugging, uncomment line below
#set -x

readonly N_ND="${set_cdn}"  # SET_MIN_CDNC; 0-->0.0e6, 1-->10.0e6, 2-->20.0e6
readonly P_PX="${set_pdx}"  # See settings below
readonly D_MS="${set_dms}"  # xDMS: L-->1.00, M-->1.50, D-->2.00

echo $'\n----- Starting run -----\n'
echo "N_ND = ${N_ND}"
echo "P_PX = ${P_PX}"
echo "D_MS = ${D_MS}"
echo $'\n-------------------------\n'

if [ "${P_PX}" == "I" ]; then
    readonly PD_OR_PI="PI"
elif [ "${P_PX}" == "D" ]; then
    readonly PD_OR_PI="PD"
fi

if [[ ${N_ND} == "00" ]]; then
    readonly SET_MIN_CDNC=0.0
elif [[ ${N_ND} == "10" ]]; then
    readonly SET_MIN_CDNC=10000000.0
elif [[ ${N_ND} == "20" ]]; then
    readonly SET_MIN_CDNC=20000000.0
fi
if [[ ${D_MS} == "00" ]]; then
    readonly SET_DMS=0.00
elif [[ ${D_MS} == "05" ]]; then
    readonly SET_DMS=0.50
elif [[ ${D_MS} == "10" ]]; then
    readonly SET_DMS=1.00
elif [[ ${D_MS} == "15" ]]; then
    readonly SET_DMS=1.50
elif [[ ${D_MS} == "20" ]]; then
    readonly SET_DMS=2.00
elif [[ ${D_MS} == "25" ]]; then
    readonly SET_DMS=2.50
elif [[ ${D_MS} == "30" ]]; then
    readonly SET_DMS=3.00
elif [[ ${D_MS} == "35" ]]; then
    readonly SET_DMS=3.50
elif [[ ${D_MS} == "40" ]]; then
    readonly SET_DMS=4.00
elif [[ ${D_MS} == "80" ]]; then
    readonly SET_DMS=8.00
fi
# --- Configuration flags ----

# Machine and project
readonly MACHINE=chrysalis
# BEFORE RUNNING:  CHANGE this to your project
readonly PROJECT="e3sm"

# Simulation
readonly COMPSET="F2010"
readonly RESOLUTION="ne30pg2_r05_IcoswISC30E3r5"
# BEFORE RUNNING : CHANGE the following CASE_NAME to desired value
readonly CASE_NAME="v3.LR.F2010.minCDNC${set_cdn}.DMSx${set_dms}.P${set_pdx}"
# If this is part of a simulation campaign, ask your group lead about using a case_group label
readonly CASE_GROUP="v3.LR"

# Code and compilation
# BEFORE RUNNING: CHANGE CHECKOUT to date string like 20240301
readonly CHECKOUT="2024-05-25"
readonly BRANCH="a67353c"
readonly CHERRY=( )
readonly DEBUG_COMPILE=false

# Run options
readonly MODEL_START_TYPE="branch"  # 'initial', 'continue', 'branch', 'hybrid'
readonly START_DATE="2009-10-01"

# Additional options for 'branch' and 'hybrid'
readonly GET_REFCASE=TRUE
readonly RUN_REFDIR="/lcrc/group/e3sm/ac.ngmahfouz/E3SMv3/n.v3.LR.F2010/archive/rest/2009-10-01-00000/"
readonly RUN_REFCASE="n.v3.LR.F2010"
readonly RUN_REFDATE="2009-10-01"   # same as MODEL_START_DATE for 'branch', can be different for 'hybrid'

# Set paths
readonly CASE_ROOT="/lcrc/group/e3sm/ac.ngmahfouz/E3SMv3/SPA2/${CASE_NAME}"
readonly CODE_ROOT="/lcrc/group/e3sm/ac.ngmahfouz/E3SMv3/n.v3.LR.F2010/code/${CHECKOUT}"
# Sub-directories
readonly CASE_BUILD_DIR=${CASE_ROOT}/build
readonly CASE_ARCHIVE_DIR=${CASE_ROOT}/archive

# Define type of run
#  short tests: 'XS_2x5_ndays', 'XS_1x10_ndays', 'S_1x10_ndays',
#               'M_1x10_ndays', 'M2_1x10_ndays', 'M80_1x10_ndays', 'L_1x10_ndays'
#  or 'production' for full simulation
# readonly run="production"
readonly run="S_6x3_nmonths"

if [ "${run}" != "production" ]; then
  echo "setting up Short test simulations: ${run}"
  # Short test simulations
  tmp=($(echo $run | tr "_" " "))
  layout=${tmp[0]}
  units=${tmp[2]}
  resubmit=$(( ${tmp[1]%%x*} -1 ))
  length=${tmp[1]##*x}

  readonly CASE_SCRIPTS_DIR=${CASE_ROOT}/tests_2/${run}/case_scripts
  readonly CASE_RUN_DIR=${CASE_ROOT}/tests_2/${run}/run
  readonly PELAYOUT=${layout}
  readonly WALLTIME="06:00:00"
  readonly STOP_OPTION=${units}
  readonly STOP_N=${length}
  readonly REST_OPTION=${STOP_OPTION}
  readonly REST_N=${STOP_N}
  readonly RESUBMIT=${resubmit}
  readonly DO_SHORT_TERM_ARCHIVING=false
else
  # Production simulation
  readonly CASE_SCRIPTS_DIR=${CASE_ROOT}/case_scripts
  readonly CASE_RUN_DIR=${CASE_ROOT}/run
  readonly PELAYOUT="custom-11"
  readonly WALLTIME="04:00:00"
  readonly STOP_OPTION="nmonths"
  readonly STOP_N="15"
  readonly REST_OPTION="nmonths"
  readonly REST_N="15"
  readonly RESUBMIT="0"
  readonly DO_SHORT_TERM_ARCHIVING=false
fi

# Coupler history
readonly HIST_OPTION="nmonths"
readonly HIST_N="1"

# Leave empty (unless you understand what it does)
readonly OLD_EXECUTABLE=""

# --- Toggle flags for what to do ----
do_fetch_code=false
do_create_newcase=true
do_case_setup=true
do_case_build=false
do_case_submit=true

readonly USER_PD_TYPE="clm" # default 2010 compset
readonly USER_PI_TYPE="mix" # default aero recommendation
if [ "${PD_OR_PI}" == "PD" ]; then
    readonly USER_PX_TYPE=${USER_PD_TYPE}
    readonly PX_YEAR="2010"
    if [ "${USER_PX_TYPE}" == "clm" ]; then
        readonly EMIS_DATE_1="20230213"
        readonly EMIS_DATE_2="20190821"
        readonly EMIS_DATE_3="20190220" # DMS
        readonly EMIS_DATE_4="20230213"  # SOAG
        readonly CLIMO_FILES_MOD_1="1x1_2010"
        readonly CLIMO_FILES_MOD_0="2010"
        readonly TRANSIENT_FILES_MOD_1="1x1_2010_clim"
        readonly TRANSIENT_FILES_MOD_0="2010_clim"
    fi
elif [ "${PD_OR_PI}" == "PI" ]; then
    readonly USER_PX_TYPE=${USER_PI_TYPE}
    readonly PX_YEAR="1850"
    if [ "${USER_PX_TYPE}" == "mix" ]; then
        readonly EMIS_DATE_1="20230213"
        readonly EMIS_DATE_2="180205"  # for transient ones
        readonly EMIS_DATE_3="20190220" # DMS
        readonly EMIS_DATE_4="20230201" # SOAG
        readonly CLIMO_FILES_MOD_1="1x1_2010-as-1850"
        readonly CLIMO_FILES_MOD_0="2010-as-1850"
        readonly TRANSIENT_FILES_MOD_1="1850-2014"
        readonly TRANSIENT_FILES_MOD_0="1850-2014"
    fi
fi

# --- Now, do the work ---

# Make directories created by this script world-readable
umask 022

# Fetch code from Github
fetch_code

# Create case
create_newcase

# Custom PE layout
custom_pelayout

# Setup
case_setup

# Build
case_build

# Configure runtime options
runtime_options

# Copy script into case_script directory for provenance
copy_script

# Submit
case_submit

# All done
echo $'\n----- All done -----\n'

}

# =======================
# Custom user_nl settings
# =======================

user_nl() {

cat << EOF >> user_nl_eam

! --------- sensitivity settings ------
p3_mincdnc              = ${SET_MIN_CDNC}
dms_emis_scale          = ${SET_DMS}

! -- nudging settings -----------------
Nudge_Model              = .True.
Nudge_Path               = '/lcrc/group/e3sm/ac.ngmahfouz/v3nm/ne30pg2L80/'
Nudge_File_Template      = 'MERRA2_ne30pg2_%y-%m-%d-%s.nc'
Nudge_Times_Per_Day      = 4                                !! nudging input data frequency
Model_Times_Per_Day      = 48                               !! should not be larger than 48 if dtime = 1800s
Nudge_Uprof              = 2                                !! 2 if nudging tendency has a vertical profile
Nudge_Ucoef              = 1.
Nudge_Vprof              = 2
Nudge_Vcoef              = 1.
Nudge_Tprof              = 0
Nudge_Tcoef              = 0.
Nudge_Qprof              = 0
Nudge_Qcoef              = 0.
Nudge_PSprof             = 0
Nudge_PScoef             = 0.
Nudge_Beg_Year           = 0000
Nudge_Beg_Month          = 1
Nudge_Beg_Day            = 1
Nudge_End_Year           = 9999
Nudge_End_Month          = 1
Nudge_End_Day            = 1
Nudge_Vwin_Lindex        = 0.                               !! activated only when Nudge_Xprof = 2 !! X = U, V, T
Nudge_Vwin_Hindex        = 80.                              !! ""
Nudge_Vwin_Ldelta        = 0.1                              !! ""
Nudge_Vwin_Hdelta        = 0.1                              !! ""
Nudge_Vwin_lo            = 0.                               !! ""
Nudge_Vwin_hi            = 1.                               !! ""
Nudge_Method             = 'Linear'
Nudge_Loc_PhysOut        = .True.                           !! nudging tendency calculated before radiation
Nudge_Tau                = 6.0                              !! relaxation time scale, unit: h
Nudge_CurrentStep        = .False.
Nudge_File_Ntime         = 1                                !! should be the same as Nudge_Times_Per_Day or 1
Nudge_Allow_Missing_File = .False.

 cosp_lite = .true.

 empty_htapes = .false.
 history_aerosol = .true.
 history_verbose = .true.
 history_aero_optics    = .true.
 history_amwg           = .true. 
 history_budget         = .true. 
 history_verbose        = .true.
 history_gaschmbudget_2D_levels = .true.
 history_UCIgaschmbudget_2D_levels = .true.

 ! -- turn on ind3 aerocom -------------
 do_aerocom_ind3     = .true.

 avgflag_pertape = 'A','I'
 nhtfrq = 0,-3
 mfilt  = 1,40

 fincl1 = 'FSNT','FLNT','FSNTC','FLNTC','FSNS','FLNS','FSNSC','FLNSC','SOLIN','FSUTOA','FSUTOAC', ! radiation fields
          'lcc','icc','clt','cdnc','icnc','lwp','aerindex','ttop', ! aerocom fields
          'CLOUDFRAC_LIQ_MICRO','NUMLIQ','CLDLIQ','CLOUDFRAC_ICE_MICRO','NUMICE','CLDICE', ! p3 fields
          'FREQZM', 'PRECL', ! other fields
          'CCN3MAIR'

 fincl2 = 'FSNT','FLNT','FSNTC','FLNTC','FSNS','FLNS','FSNSC','FLNSC','SOLIN','FSUTOA','FSUTOAC', ! radiation fields
          'lcc','icc','clt','cdnc','icnc','lwp','aerindex','ttop', ! aerocom fields
          'CLOUDFRAC_LIQ_MICRO','NUMLIQ','CLDLIQ','CLOUDFRAC_ICE_MICRO','NUMICE','CLDICE', ! p3 fields
          'FREQZM', 'PRECL', ! other fields
          'CCN3MAIR'

 ! -- chemUCI settings ------------------
 history_chemdyg_summary = .true.
 history_gaschmbudget_2D = .true.
 history_gaschmbudget_num = 6 !! no impact if  history_gaschmbudget_2D = .false.
 history_gaschmbudget_2D_levels = .true.
 history_UCIgaschmbudget_2D_levels = .true.
 
 ! -- MAM5 settings ---------------------
 is_output_interactive_volc = .true.

! -- pi or pd settings... -------------

ext_frc_cycle_yr  = ${PX_YEAR}
ext_frc_type      = 'CYCLICAL'
ext_frc_specifier = 'NO2        -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/chem_gases/2degrees/emissions-cmip6_NO2_aircraft_vertical_${CLIMO_FILES_MOD_0}_clim_1.9x2.5_c${EMIS_DATE_1}.nc',
                    'SO2        -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/DECK_ne30/cmip6_mam4_so2_elev_${TRANSIENT_FILES_MOD_1}_c${EMIS_DATE_2}.nc',
                    'SOAG0      -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/DECK_ne30/emissions-cmip6_e3sm_SOAG0_elev_${TRANSIENT_FILES_MOD_0}_1.9x2.5_c${EMIS_DATE_4}.nc',
                    'bc_a4      -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/DECK_ne30/cmip6_mam4_bc_a4_elev_${TRANSIENT_FILES_MOD_1}_c${EMIS_DATE_2}.nc',
                    'num_a1     -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/DECK_ne30/cmip6_mam4_num_a1_elev_${TRANSIENT_FILES_MOD_1}_c${EMIS_DATE_2}.nc',
                    'num_a2     -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/DECK_ne30/cmip6_mam4_num_a2_elev_${TRANSIENT_FILES_MOD_1}_c${EMIS_DATE_2}.nc',
                    'num_a4     -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/DECK_ne30/cmip6_mam4_num_a4_elev_${TRANSIENT_FILES_MOD_1}_c${EMIS_DATE_2}.nc',
                    'pom_a4     -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/DECK_ne30/cmip6_mam4_pom_a4_elev_${TRANSIENT_FILES_MOD_1}_c${EMIS_DATE_2}.nc',
                    'so4_a1     -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/DECK_ne30/cmip6_mam4_so4_a1_elev_${TRANSIENT_FILES_MOD_1}_c${EMIS_DATE_2}.nc',
                    'so4_a2     -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/DECK_ne30/cmip6_mam4_so4_a2_elev_${TRANSIENT_FILES_MOD_1}_c${EMIS_DATE_2}.nc'

srf_emis_cycle_yr = ${PX_YEAR}
srf_emis_type     = 'CYCLICAL'
srf_emis_specifier= 'C2H4       -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/chem_gases/2degrees/emissions-cmip6_e3sm_C2H4_surface_${CLIMO_FILES_MOD_0}_clim_1.9x2.5_c${EMIS_DATE_1}.nc',
                    'C2H6       -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/chem_gases/2degrees/emissions-cmip6_e3sm_C2H6_surface_${CLIMO_FILES_MOD_0}_clim_1.9x2.5_c${EMIS_DATE_1}.nc',
                    'C3H8       -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/chem_gases/2degrees/emissions-cmip6_e3sm_C3H8_surface_${CLIMO_FILES_MOD_0}_clim_1.9x2.5_c${EMIS_DATE_1}.nc',
                    'CH2O       -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/chem_gases/2degrees/emissions-cmip6_e3sm_CH2O_surface_${CLIMO_FILES_MOD_0}_clim_1.9x2.5_c${EMIS_DATE_1}.nc',
                    'CH3CHO     -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/chem_gases/2degrees/emissions-cmip6_e3sm_CH3CHO_surface_${CLIMO_FILES_MOD_0}_clim_1.9x2.5_c${EMIS_DATE_1}.nc',
                    'CH3COCH3   -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/chem_gases/2degrees/emissions-cmip6_e3sm_CH3COCH3_surface_${CLIMO_FILES_MOD_0}_clim_1.9x2.5_c${EMIS_DATE_1}.nc',
                    'CO         -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/chem_gases/2degrees/emissions-cmip6_e3sm_CO_surface_${CLIMO_FILES_MOD_0}_clim_1.9x2.5_c${EMIS_DATE_1}.nc',      
                    'ISOP       -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/chem_gases/2degrees/emissions-cmip6_e3sm_ISOP_surface_${CLIMO_FILES_MOD_0}_clim_1.9x2.5_c${EMIS_DATE_1}.nc',
                    'ISOP_VBS   -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/chem_gases/2degrees/emissions-cmip6_e3sm_ISOP_surface_${CLIMO_FILES_MOD_0}_clim_1.9x2.5_c${EMIS_DATE_1}.nc',
                    'C10H16     -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/chem_gases/2degrees/emissions-cmip6_e3sm_MTERP_surface_${CLIMO_FILES_MOD_0}_clim_1.9x2.5_c${EMIS_DATE_1}.nc',        
                    'SOAG0      -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/DECK_ne30/emissions-cmip6_e3sm_SOAG0_surf_${TRANSIENT_FILES_MOD_0}_1.9x2.5_c${EMIS_DATE_4}.nc',
                    'NO         -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/chem_gases/2degrees/emissions-cmip6_e3sm_NO_surface_${CLIMO_FILES_MOD_0}_clim_1.9x2.5_c${EMIS_DATE_1}.nc',   
                    'DMS        -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/DMSflux.${CLIMO_FILES_MOD_0}.1deg_latlon_conserv.POPmonthlyClimFromACES4BGC_c${EMIS_DATE_3}.nc',
                    'SO2        -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/DECK_ne30/cmip6_mam4_so2_surf_${TRANSIENT_FILES_MOD_1}_c${EMIS_DATE_2}.nc',
                    'bc_a4      -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/DECK_ne30/cmip6_mam4_bc_a4_surf_${TRANSIENT_FILES_MOD_1}_c${EMIS_DATE_2}.nc',
                    'num_a1     -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/DECK_ne30/cmip6_mam4_num_a1_surf_${TRANSIENT_FILES_MOD_1}_c${EMIS_DATE_2}.nc',
                    'num_a2     -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/DECK_ne30/cmip6_mam4_num_a2_surf_${TRANSIENT_FILES_MOD_1}_c${EMIS_DATE_2}.nc',
                    'num_a4     -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/DECK_ne30/cmip6_mam4_num_a4_surf_${TRANSIENT_FILES_MOD_1}_c${EMIS_DATE_2}.nc',
                    'pom_a4     -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/DECK_ne30/cmip6_mam4_pom_a4_surf_${TRANSIENT_FILES_MOD_1}_c${EMIS_DATE_2}.nc',
                    'so4_a1     -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/DECK_ne30/cmip6_mam4_so4_a1_surf_${TRANSIENT_FILES_MOD_1}_c${EMIS_DATE_2}.nc',
                    'so4_a2     -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/DECK_ne30/cmip6_mam4_so4_a2_surf_${TRANSIENT_FILES_MOD_1}_c${EMIS_DATE_2}.nc'
                    'E90        -> \$DIN_LOC_ROOT/atm/cam/chem/trop_mozart_aero/emis/chem_gases/2degrees/emissions_E90_surface_${CLIMO_FILES_MOD_0}_clim_1.9x2.5_c${EMIS_DATE_1}.nc'

EOF

cat << EOF >> user_nl_elm
 hist_empty_htapes=.true.
 check_finidat_year_consistency = .false.
 check_dynpft_consistency = .false.
 create_crop_landunit = .false.
 check_finidat_pct_consistency = .false. ! annoying lil check about bgc stuff, deviates a little, abortin'
EOF

}

patch_mpas_streams() {

echo

}

######################################################
### Most users won't need to change anything below ###
######################################################

#-----------------------------------------------------
fetch_code() {

    if [ "${do_fetch_code,,}" != "true" ]; then
        echo $'\n----- Skipping fetch_code -----\n'
        return
    fi

    echo $'\n----- Starting fetch_code -----\n'
    local path=${CODE_ROOT}
    local repo=e3sm

    echo "Cloning $repo repository branch $BRANCH under $path"
    if [ -d "${path}" ]; then
        echo "ERROR: Directory already exists. Not overwriting"
        exit 20
    fi
    mkdir -p ${path}
    pushd ${path}

    # This will put repository, with all code
    git clone git@github.com:E3SM-Project/${repo}.git .

    # Setup git hooks
    rm -rf .git/hooks
    git clone git@github.com:E3SM-Project/E3SM-Hooks.git .git/hooks
    git config commit.template .git/hooks/commit.template

    # Check out desired branch
    git checkout ${BRANCH}

    # Custom addition
    if [ "${CHERRY}" != "" ]; then
        echo ----- WARNING: adding git cherry-pick -----
        for commit in "${CHERRY[@]}"
        do
            echo ${commit}
            git cherry-pick ${commit}
        done
        echo -------------------------------------------
    fi

    # Bring in all submodule components
    git submodule update --init --recursive

    popd
}

#-----------------------------------------------------
create_newcase() {

    if [ "${do_create_newcase,,}" != "true" ]; then
        echo $'\n----- Skipping create_newcase -----\n'
        return
    fi

    echo $'\n----- Starting create_newcase -----\n'

	if [[ -z "$CASE_GROUP" ]]; then
		${CODE_ROOT}/cime/scripts/create_newcase \
			--case ${CASE_NAME} \
			--output-root ${CASE_ROOT} \
			--script-root ${CASE_SCRIPTS_DIR} \
			--handle-preexisting-dirs u \
			--compset ${COMPSET} \
			--res ${RESOLUTION} \
			--machine ${MACHINE} \
			--project ${PROJECT} \
			--walltime ${WALLTIME} \
			--pecount ${PELAYOUT}
	else
		${CODE_ROOT}/cime/scripts/create_newcase \
			--case ${CASE_NAME} \
			--case-group ${CASE_GROUP} \
			--output-root ${CASE_ROOT} \
			--script-root ${CASE_SCRIPTS_DIR} \
			--handle-preexisting-dirs u \
			--compset ${COMPSET} \
			--res ${RESOLUTION} \
			--machine ${MACHINE} \
			--project ${PROJECT} \
			--walltime ${WALLTIME} \
			--pecount ${PELAYOUT}
	fi
	

    if [ $? != 0 ]; then
      echo $'\nNote: if create_newcase failed because sub-directory already exists:'
      echo $'  * delete old case_script sub-directory'
      echo $'  * or set do_newcase=false\n'
      exit 35
    fi

}

#-----------------------------------------------------
case_setup() {

    if [ "${do_case_setup,,}" != "true" ]; then
        echo $'\n----- Skipping case_setup -----\n'
        return
    fi

    echo $'\n----- Starting case_setup -----\n'
    pushd ${CASE_SCRIPTS_DIR}

    # Setup some CIME directories
    ./xmlchange EXEROOT=${CASE_BUILD_DIR}
    ./xmlchange RUNDIR=${CASE_RUN_DIR}

    # Short term archiving
    ./xmlchange DOUT_S=${DO_SHORT_TERM_ARCHIVING^^}
    ./xmlchange DOUT_S_ROOT=${CASE_ARCHIVE_DIR}

    # Build with COSP, except for a data atmosphere (datm)
    if [ `./xmlquery --value COMP_ATM` == "datm"  ]; then
      echo $'\nThe specified configuration uses a data atmosphere, so cannot activate COSP simulator\n'
    else
      echo $'\nConfiguring E3SM to use the COSP simulator\n'
      ./xmlchange --id CAM_CONFIG_OPTS --append --val='-cosp'
    fi

    # Extracts input_data_dir in case it is needed for user edits to the namelist later
    local input_data_dir=`./xmlquery DIN_LOC_ROOT --value`

    # Custom user_nl
    user_nl

    # Finally, run CIME case.setup
    ./case.setup --reset

    popd
}

#-----------------------------------------------------
case_build() {

    pushd ${CASE_SCRIPTS_DIR}

    # do_case_build = false
    if [ "${do_case_build,,}" != "true" ]; then

        echo $'\n----- case_build -----\n'

        if [ "${OLD_EXECUTABLE}" == "" ]; then
            # Ues previously built executable, make sure it exists
            if [ -x ${CASE_BUILD_DIR}/e3sm.exe ]; then
                echo 'Skipping build because $do_case_build = '${do_case_build}
            else
                echo 'ERROR: $do_case_build = '${do_case_build}' but no executable exists for this case.'
                exit 297
            fi
        else
            # If absolute pathname exists and is executable, reuse pre-exiting executable
            if [ -x ${OLD_EXECUTABLE} ]; then
                echo 'Using $OLD_EXECUTABLE = '${OLD_EXECUTABLE}
                cp -fp ${OLD_EXECUTABLE} ${CASE_BUILD_DIR}/
            else
                echo 'ERROR: $OLD_EXECUTABLE = '$OLD_EXECUTABLE' does not exist or is not an executable file.'
                exit 297
            fi
        fi
        echo 'WARNING: Setting BUILD_COMPLETE = TRUE.  This is a little risky, but trusting the user.'
        ./xmlchange BUILD_COMPLETE=TRUE

    # do_case_build = true
    else

        echo $'\n----- Starting case_build -----\n'

        # Turn on debug compilation option if requested
        if [ "${DEBUG_COMPILE^^}" == "TRUE" ]; then
            ./xmlchange DEBUG=${DEBUG_COMPILE^^}
        fi

        # Run CIME case.build
        ./case.build

        # Some user_nl settings won't be updated to *_in files under the run directory
        # Call preview_namelists to make sure *_in and user_nl files are consistent.
	 echo $'\n----- Preview namelists -----\n'
        ./preview_namelists

    fi

    popd
}

#-----------------------------------------------------
runtime_options() {

    echo $'\n----- Starting runtime_options -----\n'
    pushd ${CASE_SCRIPTS_DIR}

    # Set simulation start date
    ./xmlchange RUN_STARTDATE=${START_DATE}

    # Segment length
    ./xmlchange STOP_OPTION=${STOP_OPTION,,},STOP_N=${STOP_N}

    # Restart frequency
    ./xmlchange REST_OPTION=${REST_OPTION,,},REST_N=${REST_N}

    # Coupler history
    ./xmlchange HIST_OPTION=${HIST_OPTION,,},HIST_N=${HIST_N}

    # Coupler budgets (always on)
    ./xmlchange BUDGETS=TRUE

    # Set resubmissions
    if (( RESUBMIT > 0 )); then
        ./xmlchange RESUBMIT=${RESUBMIT}
    fi

    # Run type
    # Start from default of user-specified initial conditions
    if [ "${MODEL_START_TYPE,,}" == "initial" ]; then
        ./xmlchange RUN_TYPE="startup"
        ./xmlchange CONTINUE_RUN="FALSE"

    # Continue existing run
    elif [ "${MODEL_START_TYPE,,}" == "continue" ]; then
        ./xmlchange CONTINUE_RUN="TRUE"

    elif [ "${MODEL_START_TYPE,,}" == "branch" ] || [ "${MODEL_START_TYPE,,}" == "hybrid" ]; then
        ./xmlchange RUN_TYPE=${MODEL_START_TYPE,,}
        ./xmlchange GET_REFCASE=${GET_REFCASE}
	./xmlchange RUN_REFDIR=${RUN_REFDIR}
        ./xmlchange RUN_REFCASE=${RUN_REFCASE}
        ./xmlchange RUN_REFDATE=${RUN_REFDATE}
        echo 'Warning: $MODEL_START_TYPE = '${MODEL_START_TYPE}
	echo '$RUN_REFDIR = '${RUN_REFDIR}
	echo '$RUN_REFCASE = '${RUN_REFCASE}
	echo '$RUN_REFDATE = '${START_DATE}

    else
        echo 'ERROR: $MODEL_START_TYPE = '${MODEL_START_TYPE}' is unrecognized. Exiting.'
        exit 380
    fi

    # Patch mpas streams files
    patch_mpas_streams

    popd
}

#-----------------------------------------------------
case_submit() {

    if [ "${do_case_submit,,}" != "true" ]; then
        echo $'\n----- Skipping case_submit -----\n'
        return
    fi

    echo $'\n----- Starting case_submit -----\n'
    pushd ${CASE_SCRIPTS_DIR}

    # Run CIME case.submit
    ./case.submit -a="--mail-type=ALL --mail-user=$USER@nersc.gov --requeue --exclude=chr-0140"

    popd
}

#-----------------------------------------------------
copy_script() {
    echo $'\n----- Saving run script for provenance -----\n'
    local script_provenance_dir=${CASE_SCRIPTS_DIR}/run_script_provenance
    mkdir -p ${script_provenance_dir}
    local this_script_name=$( basename -- "$0"; )
    local this_script_dir=$( dirname -- "$0"; )
    local script_provenance_name=${this_script_name}.`date +%Y%m%d-%H%M%S`
    cp -vp "${this_script_dir}/${this_script_name}" ${script_provenance_dir}/${script_provenance_name}
}


# =====================================================
# Custom PE layout: custom-N where N is number of nodes
# =====================================================

custom_pelayout(){

if [[ ${PELAYOUT} == custom-* ]];
then
    echo $'\n CUSTOMIZE PROCESSOR CONFIGURATION:'

    # Number of cores per node (machine specific)
    if [ "${MACHINE}" == "chrysalis" ]; then
        ncore=64
        hthrd=2  # hyper-threading
    else
        echo 'ERROR: MACHINE = '${MACHINE}' is not supported for current custom PE layout setting.'
        exit 400
    fi

    # Extract number of nodes
    tmp=($(echo ${PELAYOUT} | tr "-" " "))
    nnodes=${tmp[1]}

    # Applicable to all custom layouts
    pushd ${CASE_SCRIPTS_DIR}

    ./xmlchange NTASKS=$(( $nnodes * $ncore ))
    ./xmlchange NTHRDS=1
    ./xmlchange ROOTPE=0
    ./xmlchange MAX_MPITASKS_PER_NODE=$ncore
    ./xmlchange MAX_TASKS_PER_NODE=$(( $ncore * $hthrd))

    popd

fi

}

#-----------------------------------------------------
# Silent versions of popd and pushd
pushd() {
    command pushd "$@" > /dev/null
}
popd() {
    command popd "$@" > /dev/null
}

# Now, actually run the script
#-----------------------------------------------------
main
