#!/bin/bash -fe

# E3SM Coupled Model Group run_e3sm script template.
#
# Bash coding style inspired by:
# http://kfirlavi.herokuapp.com/blog/2012/11/14/defensive-bash-programming

set_auto="1"
set_accr="1"
set_sample_num="00"

while getopts ":o:r:e:p:" opt; do
  case $opt in
    o) set_auto=${OPTARG}
    ;;
    r) set_accr=${OPTARG}
    ;;
    p) set_sample_num=${OPTARG}
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    exit 1
    ;;
  esac

  case $OPTARG in
    -*) echo "Option $opt needs a valid argument"
    exit 1
    ;;
  esac
done

echo "Using command line arguments: -o ${set_auto} -r ${set_accr}"

main() {



readonly X_AUTO=$(python -c "a=30500*${set_auto}; print(a)")
readonly X_ACCR=$(python -c "a=117.25*${set_accr}; print(a)")
readonly SAMPLE_NUM=${set_sample_num}

# print out xauto and xacct values to stdout here for confirmation
echo "Using p3_autocon_coeff = ${X_AUTO}"
echo "Using p3_accret_coeff  = ${X_ACCR}"

# For debugging, uncomment line below
# set -x

# --- Configuration flags ----

# Machine and project
readonly MACHINE=derecho
# BEFORE RUNNING:  CHANGE this to your project
readonly PROJECT="WYOM0191"

# Simulation
readonly COMPSET="F2010"
readonly RESOLUTION="ne30pg2_r05_IcoswISC30E3r5"
# BEFORE RUNNING : CHANGE the following CASE_NAME to desired value
readonly CASE_NAME="msp2_pd_${SAMPLE_NUM}"
# If this is part of a simulation campaign, ask your group lead about using a case_group label
# readonly CASE_GROUP=""

# Code and compilation
# BEFORE RUNNING: CHANGE CHECKOUT to date string like 20240301
#readonly CHECKOUT="20240301"
#readonly BRANCH="proceed"
#readonly CHERRY=( )
readonly DEBUG_COMPILE=false

# Run options
readonly MODEL_START_TYPE="branch"  # 'initial', 'continue', 'branch', 'hybrid'
readonly START_DATE="2009-12-01"

# Additional options for 'branch' and 'hybrid'
readonly GET_REFCASE=TRUE
readonly RUN_REFDATE="2009-12-01"
readonly RUN_REFDIR="/glade/derecho/scratch/nmahfouz/2009-12-01-00000"
readonly RUN_REFCASE="ninit.rDn1aDzDcDpDk0dDs1wDtDo2v3n1"

# Set paths
readonly CODE_ROOT="${WORK}/E3SM"
#readonly CODE_ROOT="${WORK}/E3SMv3_maint2.0_nephele" #### MODIFY: Change to reflect working enironment
readonly CASE_ROOT="/glade/derecho/scratch/nmahfouz/msp2/${CASE_NAME}"
#readonly CASE_ROOT="${SCRATCH}/E3SMv3_maint2.0_nephele/${CASE_NAME}"

# Sub-directories
readonly CASE_BUILD_DIR=${CASE_ROOT}/build
readonly CASE_ARCHIVE_DIR=${CASE_ROOT}/archive

# Define type of run
#  short tests: 'XS_2x5_ndays', 'XS_1x10_ndays', 'S_1x10_ndays',
#               'M_1x10_ndays', 'M2_1x10_ndays', 'M80_1x10_ndays', 'L_1x10_ndays'
#  or 'production' for full simulation
# readonly run='custom-8_3x10_ndays'
readonly run='production'
if [ "${run}" != "production" ]; then
  echo "setting up Short test simulations: ${run}"
  # Short test simulations
  tmp=($(echo $run | tr "_" " "))
  layout=${tmp[0]}
  units=${tmp[2]}
  resubmit=$(( ${tmp[1]%%x*} -1 ))
  length=${tmp[1]##*x}

  readonly CASE_SCRIPTS_DIR=${CASE_ROOT}/tests/${run}/case_scripts
  readonly CASE_RUN_DIR=${CASE_ROOT}/tests/${run}/run
  readonly PELAYOUT=${layout}
  readonly WALLTIME="2:00:00"
  readonly STOP_OPTION=${units}
  readonly STOP_N=${length}
  readonly REST_OPTION=${STOP_OPTION}
  readonly REST_N=${STOP_N}
  readonly RESUBMIT=${resubmit}
  readonly DO_SHORT_TERM_ARCHIVING=false

else

  # Production simulation
  readonly CASE_SCRIPTS_DIR=${CASE_ROOT}/case_scripts
  readonly CASE_RUN_DIR=${CASE_ROOT}/run
  readonly PELAYOUT="custom-8"
  readonly WALLTIME="05:00:00"
  readonly STOP_OPTION="nmonths"
  readonly STOP_N="13"
  readonly REST_OPTION="nmonths"
  readonly REST_N="14"
  readonly RESUBMIT="0"
  readonly DO_SHORT_TERM_ARCHIVING=false
fi

# Coupler history
readonly HIST_OPTION="nmonths"
readonly HIST_N="14"

# Leave empty (unless you understand what it does)
readonly OLD_EXECUTABLE="/glade/derecho/scratch/nmahfouz/test/msp1_pd_/build/e3sm.exe"

# --- Toggle flags for what to do ----
do_fetch_code=false
do_create_newcase=true
do_case_setup=true
do_case_build=false
do_case_submit=true

# --- Now, do the work ---

# Make directories created by this script world-readable
umask 022

# Fetch code from Github
fetch_code

# Create case
create_newcase

# Custom PE layout - JMN: added
custom_pelayout

# Setup
case_setup

# Build
case_build

# Configure runtime options
runtime_options

# Copy script into case_script directory for provenance
# copy_script

# Submit
case_submit

# All done
echo $'\n----- All done -----\n'

}

# =======================
# Custom user_nl settings
# =======================

user_nl() {

cat << EOF >> user_nl_eam

! ------- ppe stuff begin
p3_autocon_coeff        = ${X_AUTO}
p3_accret_coeff         = ${X_ACCR}
! ------- ppe stuff done

 cosp_lite = .true.

 empty_htapes = .true.
 
! -- set these just in case -----------
history_verbose     = .true.
history_aerosol     = .true.
history_aero_optics = .true.

! -- turn on ind3 aerocom -------------
do_aerocom_ind3     = .true.

! -- do double radiation calls --------
rad_diag_1 = 'A:H2OLNZ:H2O','N:O2:O2','N:CO2:CO2','A:O3:O3','A:N2OLNZ:N2O','A:CH4LNZ:CH4','N:CFC11:CFC11','N:CFC12:CFC12'

! -- output settings ------------------
nhtfrq          =    0 , -3, -1, -1 
mfilt           =    1 , 40, 120, 120
avgflag_pertape =   'A', 'I', 'I', 'A'

 ! -- variables to output -------------
 ! -- note: if changing these, also change in user_nl_elm below -----
fincl1          =   'OCNFRAC',
                    'angstrm', 'aerindex', 'cod',
                    'cdnc', 'icnc',
                    'cdnc2', 'icnc2',
                    'cdnum', 'icnum',
                    'clt', 'lcc', 'cdr', 'icr', 'icc', 'ccn',
                    'clt2', 'lcc2', 'cdr2', 'icr2', 'icc2', 'ccn2',
                    'ttop', 'ptop', 'htop',
                    'ttop2', 'ptop2', 'htop2',
                    'autoconv', 'accretn', 
                    'cdr', 'colrv', 'lwp', 'iwp', 'lwp2', 'iwp2', 'iwpbf','lwpbf', 'cdnumbf', 'icnumbf',
                    'aod400', 'aod700',
                    'colccn.1', 'colccn.3', 'ccn.1bl', 'ccn.3bl', 'intccn',
                    'CLDTOT', 'AODVIS',
                    'SOLIN',
                    'FLNTC_d1', 'FLNTC', 'FLNT_d1', 'FLNT', 'FLUTC','FLUT',
                    'FSNTC_d1', 'FSNTC', 'FSNT_d1', 'FSNT', 'FSNTOA', 'FSUTOAC_d1', 'FSUTOAC', 'FSUTOA_d1', 'FSUTOA',
                    'OMEGA500', 'OMEGA700', 'TH7001000', 'U850', 'V850',
                    'FREQZM', 'PRECL', 'PRECT', 'PRECZ', 'PRECC'
fincl2          =   'OCNFRAC',
                    'angstrm', 'aerindex', 'cod',
                    'cdnc', 'icnc',
                    'cdnc2', 'icnc2',
                    'cdnum', 'icnum',
                    'clt', 'lcc', 'cdr', 'icr', 'icc', 'ccn',
                    'clt2', 'lcc2', 'cdr2', 'icr2', 'icc2', 'ccn2',
                    'ttop', 'ptop', 'htop',
                    'ttop2', 'ptop2', 'htop2',
                    'autoconv', 'accretn', 
                    'cdr', 'colrv', 'lwp', 'iwp', 'lwp2', 'iwp2', 'iwpbf','lwpbf', 'cdnumbf', 'icnumbf',
                    'aod400', 'aod700',
                    'colccn.1', 'colccn.3', 'ccn.1bl', 'ccn.3bl', 'intccn',
                    'CLDTOT', 'AODVIS',
                    'SOLIN',
                    'FLNTC_d1', 'FLNTC', 'FLNT_d1', 'FLNT', 'FLUTC','FLUT',
                    'FSNTC_d1', 'FSNTC', 'FSNT_d1', 'FSNT', 'FSNTOA', 'FSUTOAC_d1', 'FSUTOAC', 'FSUTOA_d1', 'FSUTOA',
                    'OMEGA500', 'OMEGA700', 'TH7001000', 'U850', 'V850',
                    'FREQZM', 'PRECL', 'PRECT', 'PRECZ', 'PRECC'
 fincl3         = 'PRECT', 'TREFHT'
 fincl4         = 'PRECT', 'TREFHT' 

! -- nudging settings -----------------
Nudge_Model              = .True.
Nudge_Path               = '/glade/derecho/scratch/nmahfouz/ne30pg2L80/'
Nudge_File_Template      = 'MERRA2_ne30pg2_%y-%m-%d-%s.nc'
Nudge_Times_Per_Day      = 4 
Model_Times_Per_Day      = 48
Nudge_Uprof              = 2                                !! 2 if nudging tendency has a vertical profile
Nudge_Ucoef              = 1.
Nudge_Vprof              = 2
Nudge_Vcoef              = 1.
Nudge_Tprof              = 0
Nudge_Tcoef              = 0.
Nudge_Qprof              = 0
Nudge_Qcoef              = 0.
Nudge_PSprof             = 0
Nudge_PScoef             = 0.
Nudge_Beg_Year           = 0000
Nudge_Beg_Month          = 1
Nudge_Beg_Day            = 1
Nudge_End_Year           = 9999
Nudge_End_Month          = 1
Nudge_End_Day            = 1
Nudge_Vwin_Lindex        = 0.                               !! activated only when Nudge_Xprof = 2 !! X = U, V, T
Nudge_Vwin_Hindex        = 80.                              !! ""
Nudge_Vwin_Ldelta        = 0.1                              !! ""
Nudge_Vwin_Hdelta        = 0.1                              !! ""
Nudge_Vwin_lo            = 0.                               !! ""
Nudge_Vwin_hi            = 1.                               !! ""
Nudge_Method             = 'Linear'
Nudge_Loc_PhysOut        = .True.                           !! nudging tendency calculated before radiation
Nudge_Tau                = 6.0                              !! relaxation time scale, unit: h
Nudge_CurrentStep        = .False.
Nudge_File_Ntime         = 1                                !! should be the same as Nudge_Times_Per_Day or 1
Nudge_Allow_Missing_File = .False.

 ! -- chemUCI settings ------------------
 history_chemdyg_summary = .true.
 history_gaschmbudget_2D = .false.
 history_gaschmbudget_2D_levels = .false.
 history_gaschmbudget_num = 6 !! no impact if  history_gaschmbudget_2D = .false.

 ! -- MAM5 settings ------------------
 is_output_interactive_volc = .true.

 ! -- Parameter values swapped by Dakota ----------
 
EOF

cat << EOF >> user_nl_elm
 hist_empty_htapes = .true.
 check_finidat_year_consistency = .false.
 check_dynpft_consistency = .false.
 create_crop_landunit = .false.
EOF

}

patch_mpas_streams() {

echo

}

# =====================================================
# Custom PE layout: custom-N where N is number of nodes
# =====================================================
# JMN: added - from https://portal.nersc.gov/project/e3sm/Tutorials/2024/scripts/run.v3.LR.historical_0101.pm-cpu.sh

custom_pelayout(){

if [[ ${PELAYOUT} == custom-* ]];
then
    echo $'\n CUSTOMIZE PROCESSOR CONFIGURATION:'

    # Number of cores per node (machine specific)
    if [ "${MACHINE}" == "chrysalis" ]; then
        ncore=64
        hthrd=1  # hyper-threading, default to non-threading
    elif [ "${MACHINE}" == "pm-cpu" ]; then
        ncore=128
        hthrd=1  # including pm-cpu
    # JMN: added for derecho 
    elif [ "${MACHINE}" == "derecho" ]; then
	  ncore=128
	  hthrd=1 
    fi

    # Extract number of nodes
    tmp=($(echo ${PELAYOUT} | tr "-" " "))
    nnodes=${tmp[1]}

    # Applicable to all custom layouts
    pushd ${CASE_SCRIPTS_DIR}
    ./xmlchange NTASKS=1
    ./xmlchange NTHRDS=1
    ./xmlchange ROOTPE=0
    ./xmlchange MAX_MPITASKS_PER_NODE=$ncore
    ./xmlchange MAX_TASKS_PER_NODE=$(( $ncore * $hthrd))

    # Layout-specific customization
    if [ "${nnodes}" == "1" ]; then

       echo Using custom 1 nodes layout with pm-cpu

      ./xmlchange CPL_NTASKS=128
      ./xmlchange ATM_NTASKS=128
      ./xmlchange OCN_NTASKS=128
      ./xmlchange OCN_ROOTPE=0

      ./xmlchange LND_NTASKS=128
      ./xmlchange ROF_NTASKS=128
      ./xmlchange ICE_NTASKS=128
      ./xmlchange LND_ROOTPE=0
      ./xmlchange ROF_ROOTPE=0

    elif [ "${nnodes}" == "2" ]; then

       echo Using custom 2 nodes layout with pm-cpu

      ./xmlchange CPL_NTASKS=256
      ./xmlchange ATM_NTASKS=256
      ./xmlchange OCN_NTASKS=256
      ./xmlchange OCN_ROOTPE=0

      ./xmlchange LND_NTASKS=256
      ./xmlchange ROF_NTASKS=256
      ./xmlchange ICE_NTASKS=256
      ./xmlchange LND_ROOTPE=0
      ./xmlchange ROF_ROOTPE=0

    elif [ "${nnodes}" == "4" ]; then

       echo Using custom 4 nodes layout with pm-cpu

      ./xmlchange CPL_NTASKS=512
      ./xmlchange ATM_NTASKS=512
      ./xmlchange OCN_NTASKS=512
      ./xmlchange OCN_ROOTPE=0

      ./xmlchange LND_NTASKS=512
      ./xmlchange ROF_NTASKS=512
      ./xmlchange ICE_NTASKS=512
      ./xmlchange LND_ROOTPE=0
      ./xmlchange ROF_ROOTPE=0

    elif [ "${nnodes}" == "8" ]; then

       echo Using custom 8 nodes layout with pm-cpu

      ./xmlchange CPL_NTASKS=1024
      ./xmlchange ATM_NTASKS=1024
      ./xmlchange OCN_NTASKS=1024
      ./xmlchange OCN_ROOTPE=0

      ./xmlchange LND_NTASKS=1024
      ./xmlchange ROF_NTASKS=1024
      ./xmlchange ICE_NTASKS=1024
      ./xmlchange LND_ROOTPE=0
      ./xmlchange ROF_ROOTPE=0


    # JMN - added custom-10
    elif [ "${nnodes}" == "10" ]; then

       echo Using custom 10 nodes layout with pm-cpu

      ./xmlchange CPL_NTASKS=1280
      ./xmlchange ATM_NTASKS=1280
      ./xmlchange OCN_NTASKS=1280
      ./xmlchange OCN_ROOTPE=0

      ./xmlchange LND_NTASKS=1280
      ./xmlchange ROF_NTASKS=1280
      ./xmlchange ICE_NTASKS=1280
      ./xmlchange LND_ROOTPE=0
      ./xmlchange ROF_ROOTPE=0

    else

       echo 'ERRROR: unsupported layout '${PELAYOUT}
       exit 401

    fi

    popd

fi

}

# #####################################################
# ## Most users won't need to change anything below ###
# #####################################################

#-----------------------------------------------------
fetch_code() {

    if [ "${do_fetch_code,,}" != "true" ]; then
        echo $'\n----- Skipping fetch_code -----\n'
        return
    fi

    echo $'\n----- Starting fetch_code -----\n'
    local path=${CODE_ROOT}
    local repo=e3sm

    echo "Cloning $repo repository branch $BRANCH under $path"
    if [ -d "${path}" ]; then
        echo "ERROR: Directory already exists. Not overwriting"
        exit 20
    fi
    mkdir -p ${path}
    pushd ${path}

    # This will put repository, with all code
    git clone git@github.com:E3SM-Project/${repo}.git .

    # Setup git hooks
    rm -rf .git/hooks
    git clone git@github.com:E3SM-Project/E3SM-Hooks.git .git/hooks
    git config commit.template .git/hooks/commit.template

    # Check out desired branch
    git checkout ${BRANCH}

    # Custom addition
    if [ "${CHERRY}" != "" ]; then
        echo ----- WARNING: adding git cherry-pick -----
        for commit in "${CHERRY[@]}"
        do
            echo ${commit}
            git cherry-pick ${commit}
        done
        echo -------------------------------------------
    fi

    # Bring in all submodule components
    git submodule update --init --recursive

    popd
}

#-----------------------------------------------------
create_newcase() {

    if [ "${do_create_newcase,,}" != "true" ]; then
        echo $'\n----- Skipping create_newcase -----\n'
        return
    fi

    echo $'\n----- Starting create_newcase -----\n'

	if [[ -z "$CASE_GROUP" ]]; then
		${CODE_ROOT}/cime/scripts/create_newcase \
			--case ${CASE_NAME} \
			--output-root ${CASE_ROOT} \
			--script-root ${CASE_SCRIPTS_DIR} \
			--handle-preexisting-dirs u \
			--compset ${COMPSET} \
			--res ${RESOLUTION} \
			--machine ${MACHINE} \
			--project ${PROJECT} \
			--walltime ${WALLTIME} \
			--pecount ${PELAYOUT}
	else
		${CODE_ROOT}/cime/scripts/create_newcase \
			--case ${CASE_NAME} \
			--case-group ${CASE_GROUP} \
			--output-root ${CASE_ROOT} \
			--script-root ${CASE_SCRIPTS_DIR} \
			--handle-preexisting-dirs u \
			--compset ${COMPSET} \
			--res ${RESOLUTION} \
			--machine ${MACHINE} \
			--project ${PROJECT} \
			--walltime ${WALLTIME} \
			--pecount ${PELAYOUT}
	fi
	

    if [ $? != 0 ]; then
      echo $'\nNote: if create_newcase failed because sub-directory already exists:'
      echo $'  * delete old case_script sub-directory'
      echo $'  * or set do_newcase=false\n'
      exit 35
    fi

}

#-----------------------------------------------------
case_setup() {

    if [ "${do_case_setup,,}" != "true" ]; then
        echo $'\n----- Skipping case_setup -----\n'
        return
    fi

    echo $'\n----- Starting case_setup -----\n'
    pushd ${CASE_SCRIPTS_DIR}

    # Setup some CIME directories
    ./xmlchange EXEROOT=${CASE_BUILD_DIR}
    ./xmlchange RUNDIR=${CASE_RUN_DIR}

    # Short term archiving
    ./xmlchange DOUT_S=${DO_SHORT_TERM_ARCHIVING^^}
    ./xmlchange DOUT_S_ROOT=${CASE_ARCHIVE_DIR}

    # Build with COSP, except for a data atmosphere (datm)
    if [ `./xmlquery --value COMP_ATM` == "datm"  ]; then
      echo $'\nThe specified configuration uses a data atmosphere, so cannot activate COSP simulator\n'
    else
      echo $'\nConfiguring E3SM to use the COSP simulator\n'
      ./xmlchange --id CAM_CONFIG_OPTS --append --val='-cosp'
    fi

    # Extracts input_data_dir in case it is needed for user edits to the namelist later
    local input_data_dir=`./xmlquery DIN_LOC_ROOT --value`

    # Custom user_nl
    user_nl

    # Finally, run CIME case.setup
    ./case.setup --reset

    popd
}

#-----------------------------------------------------
case_build() {

    pushd ${CASE_SCRIPTS_DIR}

    # do_case_build = false
    if [ "${do_case_build,,}" != "true" ]; then

        echo $'\n----- case_build -----\n'

        if [ "${OLD_EXECUTABLE}" == "" ]; then
            # Ues previously built executable, make sure it exists
            if [ -x ${CASE_BUILD_DIR}/e3sm.exe ]; then
                echo 'Skipping build because $do_case_build = '${do_case_build}
            else
                echo 'ERROR: $do_case_build = '${do_case_build}' but no executable exists for this case.'
                exit 297
            fi
        else
            # If absolute pathname exists and is executable, reuse pre-exiting executable
            if [ -x ${OLD_EXECUTABLE} ]; then
                echo 'Using $OLD_EXECUTABLE = '${OLD_EXECUTABLE}
                cp -fp ${OLD_EXECUTABLE} ${CASE_BUILD_DIR}/
            else
                echo 'ERROR: $OLD_EXECUTABLE = '$OLD_EXECUTABLE' does not exist or is not an executable file.'
                exit 297
            fi
        fi
        echo 'WARNING: Setting BUILD_COMPLETE = TRUE.  This is a little risky, but trusting the user.'
        ./xmlchange BUILD_COMPLETE=TRUE

    # do_case_build = true
    else

        echo $'\n----- Starting case_build -----\n'

        # Turn on debug compilation option if requested
        if [ "${DEBUG_COMPILE^^}" == "TRUE" ]; then
            ./xmlchange DEBUG=${DEBUG_COMPILE^^}
        fi

        # Run CIME case.build
        ./case.build

        # Some user_nl settings won't be updated to *_in files under the run directory
        # Call preview_namelists to make sure *_in and user_nl files are consistent.
	 echo $'\n----- Preview namelists -----\n'
        ./preview_namelists

    fi

    popd
}

#-----------------------------------------------------
runtime_options() {

    echo $'\n----- Starting runtime_options -----\n'
    pushd ${CASE_SCRIPTS_DIR}

    # Set simulation start date
    ./xmlchange RUN_STARTDATE=${START_DATE}

    # Segment length
    ./xmlchange STOP_OPTION=${STOP_OPTION,,},STOP_N=${STOP_N}

    # Restart frequency
    ./xmlchange REST_OPTION=${REST_OPTION,,},REST_N=${REST_N}

    # Coupler history
    ./xmlchange HIST_OPTION=${HIST_OPTION,,},HIST_N=${HIST_N}

    # Coupler budgets (always on)
    ./xmlchange BUDGETS=TRUE

    # Set resubmissions
    if (( RESUBMIT > 0 )); then
        ./xmlchange RESUBMIT=${RESUBMIT}
    fi

    # Run type
    # Start from default of user-specified initial conditions
    if [ "${MODEL_START_TYPE,,}" == "initial" ]; then
        ./xmlchange RUN_TYPE="startup"
        ./xmlchange CONTINUE_RUN="FALSE"

    # Continue existing run
    elif [ "${MODEL_START_TYPE,,}" == "continue" ]; then
        ./xmlchange CONTINUE_RUN="TRUE"

    elif [ "${MODEL_START_TYPE,,}" == "branch" ] || [ "${MODEL_START_TYPE,,}" == "hybrid" ]; then
        ./xmlchange RUN_TYPE=${MODEL_START_TYPE,,}
        ./xmlchange GET_REFCASE=${GET_REFCASE}
	./xmlchange RUN_REFDIR=${RUN_REFDIR}
        ./xmlchange RUN_REFCASE=${RUN_REFCASE}
        ./xmlchange RUN_REFDATE=${RUN_REFDATE}
        echo 'Warning: $MODEL_START_TYPE = '${MODEL_START_TYPE}
	echo '$RUN_REFDIR = '${RUN_REFDIR}
	echo '$RUN_REFCASE = '${RUN_REFCASE}
	echo '$RUN_REFDATE = '${START_DATE}

    else
        echo 'ERROR: $MODEL_START_TYPE = '${MODEL_START_TYPE}' is unrecognized. Exiting.'
        exit 380
    fi

    # Patch mpas streams files
    patch_mpas_streams

    popd
}

#-----------------------------------------------------
case_submit() {

    if [ "${do_case_submit,,}" != "true" ]; then
        echo $'\n----- Skipping case_submit -----\n'
        return
    fi

    echo $'\n----- Starting case_submit -----\n'
    pushd ${CASE_SCRIPTS_DIR}

    # Run CIME case.submit (JMN - ADDED: -M fail to request all emails)
    ./case.submit -M all

    popd
}

#-----------------------------------------------------
# copy_script() {

#     echo $'\n----- Saving run script for provenance -----\n'

#     local script_provenance_dir=${CASE_SCRIPTS_DIR}/run_script_provenance
#     mkdir -p ${script_provenance_dir}
#     local this_script_name=`basename $0`
#     local script_provenance_name=${this_script_name}.`date +%Y%m%d-%H%M%S`
#     cp -vp ${this_script_name} ${script_provenance_dir}/${script_provenance_name}

# }

#-----------------------------------------------------
# Silent versions of popd and pushd
pushd() {
    command pushd "$@" > /dev/null
}
popd() {
    command popd "$@" > /dev/null
}

# Now, actually run the script
#-----------------------------------------------------
main
